CREATE TABLE report_special_processing_records (
    id BIGINT NOT NULL AUTO_INCREMENT,
    record_no VARCHAR(32) NOT NULL,
    report_process_code VARCHAR(64) NOT NULL,
    report_process_name_snapshot VARCHAR(100) NOT NULL,
    report_period DATE NULL,
    summary VARCHAR(200) NULL,
    processing_content TEXT NULL,
    processing_script LONGTEXT NULL,
    script_sha256 CHAR(64) NULL,
    status VARCHAR(20) NOT NULL,
    special_handling_at DATETIME(6) NULL,
    handler_user_id VARCHAR(64) NULL,
    handler_username_snapshot VARCHAR(100) NULL,
    handler_display_name_snapshot VARCHAR(100) NULL,
    creator_user_id VARCHAR(64) NOT NULL,
    creator_username_snapshot VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_by_user_id VARCHAR(64) NOT NULL,
    updated_by_username_snapshot VARCHAR(100) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    completed_at DATETIME(6) NULL,
    voided_at DATETIME(6) NULL,
    voided_by_user_id VARCHAR(64) NULL,
    void_reason VARCHAR(500) NULL,
    workflow_status VARCHAR(32) NOT NULL,
    workflow_instance_id VARCHAR(64) NULL,
    workflow_version INT NOT NULL,
    row_version BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_report_special_processing_records_no (record_no),
    KEY ix_rsp_process_period_time (report_process_code, report_period, special_handling_at),
    KEY ix_rsp_status_time (status, special_handling_at),
    KEY ix_rsp_handler_status (handler_user_id, status),
    KEY ix_rsp_creator_status (creator_user_id, status),
    KEY ix_rsp_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- module-statement-break
CREATE TABLE report_special_processing_reports (
    id BIGINT NOT NULL AUTO_INCREMENT,
    record_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    report_name VARCHAR(200) NOT NULL,
    report_name_normalized VARCHAR(200) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_rsp_reports_sequence (record_id, sequence_no),
    UNIQUE KEY uq_rsp_reports_name (record_id, report_name_normalized),
    KEY ix_rsp_reports_record (record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- module-statement-break
CREATE TABLE report_special_processing_audit_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    record_id BIGINT NOT NULL,
    record_no_snapshot VARCHAR(32) NOT NULL,
    action_code VARCHAR(32) NOT NULL,
    operator_user_id VARCHAR(64) NOT NULL,
    operator_username_snapshot VARCHAR(100) NOT NULL,
    operator_display_name_snapshot VARCHAR(100) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    from_status VARCHAR(20) NULL,
    to_status VARCHAR(20) NULL,
    changed_fields_json TEXT NOT NULL,
    action_summary VARCHAR(1000) NOT NULL,
    request_id VARCHAR(64) NULL,
    PRIMARY KEY (id),
    KEY ix_rsp_audit_record_time (record_id, occurred_at),
    KEY ix_rsp_audit_operator_time (operator_user_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
