CREATE TABLE report_special_processing_records (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '特殊处理记录主键',
    record_no VARCHAR(32) NOT NULL COMMENT '特殊处理记录编号',
    report_process_code VARCHAR(64) NOT NULL COMMENT '报送流程编码',
    report_process_name_snapshot VARCHAR(100) NOT NULL COMMENT '报送流程名称快照',
    report_period DATE NULL COMMENT '报告期',
    summary VARCHAR(200) NULL COMMENT '特殊处理事项摘要',
    processing_content TEXT NULL COMMENT '特殊处理内容',
    processing_script LONGTEXT NULL COMMENT '特殊处理脚本文本，仅存储不执行',
    script_sha256 CHAR(64) NULL COMMENT '脚本文本 SHA-256 摘要',
    status VARCHAR(20) NOT NULL COMMENT '处理状态',
    special_handling_at DATETIME(6) NULL COMMENT '特殊处理发生时间',
    handler_user_id VARCHAR(64) NULL COMMENT '处理人用户 ID',
    handler_username_snapshot VARCHAR(100) NULL COMMENT '处理人用户名快照',
    handler_display_name_snapshot VARCHAR(100) NULL COMMENT '处理人显示名称快照',
    creator_user_id VARCHAR(64) NOT NULL COMMENT '创建人用户 ID',
    creator_username_snapshot VARCHAR(100) NOT NULL COMMENT '创建人用户名快照',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    updated_by_user_id VARCHAR(64) NOT NULL COMMENT '最后更新人用户 ID',
    updated_by_username_snapshot VARCHAR(100) NOT NULL COMMENT '最后更新人用户名快照',
    updated_at DATETIME(6) NOT NULL COMMENT '最后更新时间',
    completed_at DATETIME(6) NULL COMMENT '完成时间',
    voided_at DATETIME(6) NULL COMMENT '作废时间',
    voided_by_user_id VARCHAR(64) NULL COMMENT '作废操作人用户 ID',
    void_reason VARCHAR(500) NULL COMMENT '作废原因',
    workflow_status VARCHAR(32) NOT NULL COMMENT '外部工作流状态',
    workflow_instance_id VARCHAR(64) NULL COMMENT '外部工作流实例 ID',
    workflow_version INT NOT NULL COMMENT '外部工作流版本号',
    row_version BIGINT NOT NULL COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uq_report_special_processing_records_no (record_no),
    KEY ix_rsp_process_period_time (report_process_code, report_period, special_handling_at),
    KEY ix_rsp_status_time (status, special_handling_at),
    KEY ix_rsp_handler_status (handler_user_id, status),
    KEY ix_rsp_creator_status (creator_user_id, status),
    KEY ix_rsp_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报表特殊处理主记录表'
-- module-statement-break
CREATE TABLE report_special_processing_reports (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '涉及报表明细主键',
    record_id BIGINT NOT NULL COMMENT '关联特殊处理记录主键',
    sequence_no INT NOT NULL COMMENT '报表显示顺序',
    report_name VARCHAR(200) NOT NULL COMMENT '报表名称',
    report_name_normalized VARCHAR(200) NOT NULL COMMENT '用于去重匹配的规范化报表名称',
    created_at DATETIME(6) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uq_rsp_reports_sequence (record_id, sequence_no),
    UNIQUE KEY uq_rsp_reports_name (record_id, report_name_normalized),
    KEY ix_rsp_reports_record (record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报表特殊处理涉及报表明细表'
-- module-statement-break
CREATE TABLE report_special_processing_audit_logs (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '审计日志主键',
    record_id BIGINT NOT NULL COMMENT '关联特殊处理记录主键',
    record_no_snapshot VARCHAR(32) NOT NULL COMMENT '特殊处理记录编号快照',
    action_code VARCHAR(32) NOT NULL COMMENT '操作类型编码',
    operator_user_id VARCHAR(64) NOT NULL COMMENT '操作人用户 ID',
    operator_username_snapshot VARCHAR(100) NOT NULL COMMENT '操作人用户名快照',
    operator_display_name_snapshot VARCHAR(100) NOT NULL COMMENT '操作人显示名称快照',
    occurred_at DATETIME(6) NOT NULL COMMENT '操作发生时间',
    from_status VARCHAR(20) NULL COMMENT '操作前处理状态',
    to_status VARCHAR(20) NULL COMMENT '操作后处理状态',
    changed_fields_json TEXT NOT NULL COMMENT '变更字段 JSON',
    action_summary VARCHAR(1000) NOT NULL COMMENT '操作摘要',
    request_id VARCHAR(64) NULL COMMENT '请求追踪 ID',
    PRIMARY KEY (id),
    KEY ix_rsp_audit_record_time (record_id, occurred_at),
    KEY ix_rsp_audit_operator_time (operator_user_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报表特殊处理操作审计日志表'
